baseURL: "https://www.spokeneagle.com/"
languageCode: 'en-us'
title: "Spoken Eagle"
theme: 'PaperMod'


menu:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: categories
      pageRef: /categories
      weight: 20
    - name: tags
      pageRef: /tags
      weight: 30
    - name: posts
      pageRef: /posts
      weight: 40
    - name: Contact
      pageRef: /contact
      weight: 50
    - name: About
      pageRef: /about
      weight: 60



Params:
  ShowShareButtons: true
  ShowComments: true
  ShowMeta: true
  ShowActions: true
  ShowTOC: false
  ShowRelated: true
  ShowReadingTime: true
  hideSummary: true
  ShowBreadCrumbs: true

  label:
    text: 'Spoken Eagle'
    icon: '/eagle.png'
