baseURL: "https://www.spokeneagle.com/"
languageCode: 'en-us'
title: "Spoken Eagle"
theme: 'PaperMod'

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

menu:
  main:
    - name: Home
      pageRef: /
      weight: 10
    - name: News
      pageRef: /news
      weight: 15
    - name: Categories
      pageRef: /categories
      weight: 20
    - name: Create Your Article
      pageRef: /create-your-article
      weight: 30
    - name: Apps
      pageRef: /apps
      weight: 40
    - name: About
      pageRef: /about
      weight: 50


Params:
  ShowShareButtons: true
  ShowComments: true
  ShowMeta: true
  ShowActions: true
  ShowTOC: false
  ShowRelated: true
  ShowReadingTime: true
  hideSummary: true
  ShowBreadCrumbs: true
  keywords: ["Spoken Eagle","News","Tech","Music","Finance","Blogging"]
  description: "Discover the latest news and trends in the world of blogging.
   Read our blog posts to learn about everything from music to finance, Tech and News. Spoken Eagle"


  label:
    text: 'Spoken Eagle'
    icon: '/eagle.png'
